academy:

  replicaCount: 1

  image:
    repository: ${deployment_image}
    pullPolicy: IfNotPresent

  serviceAccountName: ${service_account}
  service:
    type: ClusterIP
    port: 80

mysql:

  image:
    repository: fsadykov/centos_mysql
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3306
    serviceName: academy-mysql-service

nameOverride: ""
fullnameOverride: ""


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  path: /
  hosts:
    - ${deployment_endpoint}
  tls:
   - secretName: academy-chart-tls
     hosts:
       - ${deployment_endpoint}

globalEnvironments:
  enabled: true
  environments:

  - name: MYSQL_USER
    value: ${mysql_user}

  - name: MYSQL_DATABASE
    value: ${mysql_database}

  - name: MYSQL_PASSWORD
    value: ${mysql_password}

  - name: ADMIN_USER
    value: ${admin_user}

  - name: ADMIN_PASSWORD
    value: ${admin_password}

  - name: MYSQL_ROOT_PASSWORD
    value: ${mysql_root_password}

  - name: APPLICATION_ENDPOINT
    value: ${application_url}

  - name: GIT_TOKEN
    value: ${github_token}

  - name: SOCIAL_AUTH_GITHUB_KEY
    value: ${github_client_id}

  - name: SOCIAL_AUTH_GITHUB_SECRET
    value: ${github_client_secret}

  - name: SECRET_KEY
    value: ${application_secret}
  
  - name: VIMEO_CLIENT_SECRET
    value: ${vimeo_client_secret}

  - name: VIMEO_ACCESS_TOKEN
    value: ${vimeo_access_token}

  - name: VIMEO_CLIENT_ID
    value: ${vimeo_client_id}

imageSecret:
  enabled: true
  allSecrets:
  - name: nexus-creds

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}