version: '3.3'
services:
  academy:
    # depends_on:
    #    - mysql
    container_name: academy
    build: ./
    volumes:
      - ./academy:/website
    ports:
      - "5000:5000"
    links:
      - "mysql:database"
    environment:
      SOCIAL_AUTH_GITHUB_KEY: 12a5ef9d9cd3a7ab1d67
      SOCIAL_AUTH_GITHUB_SECRET: 3a02672b7cdc6bb56d3e335f6a5a48de96a85b25
      ADMIN_USER: firasjb
      ADMIN_PASSWORD: firasjb*
      MYSQL_ROOT_PASSWORD: LocalPass
      MYSQL_DATABASE: academy
      MYSQL_USER: academy
      MYSQL_PASSWORD: LocalPass
      MYSQL_HOST: database
      ENVIRONMENT: dev
  mysql:
    container_name: mysql
    image: fsadykov/centos_mysql
    # ports:
    #   - "3306:3306"
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: LocalPass
      MYSQL_DATABASE: academy
      MYSQL_USER: academy
      MYSQL_PASSWORD: LocalPass
# volumes:
#   db_data: {}