# Generated by Django 3.0.3 on 2020-05-25 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200525_0610'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
