# Generated by Django 3.0.3 on 2020-05-25 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('main', '0006_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='accounting.Plans'),
        ),
    ]
