# Generated by Django 3.0.3 on 2020-05-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200525_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='plan',
        ),
        migrations.AddField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(default='Basic', max_length=60),
        ),
    ]
