# Generated by Django 3.0.3 on 2020-05-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200526_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='payment_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
